### ISSUE TITLE
error trying to get balance with multiples wallets

### ISSUE THREAD

**Issue by Mairkur** [vulpemventures/nigiri#104]
Hi, I'm trying to work with multiple wallets in nigiri to be able to see the balance of the wallet changing between transactions.

So I created a new wallet using : 
`nigiri rpc --liquid createwallet "walletname"`

I then tried to see the balance of the new wallet by using : 
`nigiri rpc --liquid getbalance "walletname" 0 true`

which returns the following error : 
```
error code: -19
error message:
Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path).
Try adding "-rpcwallet=<filename>" option to elements-cli command line.
Error: exit status 19
Usage:
  nigiri rpc <command> [flags]

Flags:
  -h, --help     help for rpc
      --liquid   Set to use liquid node

Global Flags:
      --datadir string   Set nigiri default directory (default "...")
```

So I tried to specify the wallet I want to obtain the balance : 

`nigiri rpc --liquid getbalance -rpcwallet="walletname"` 

which lead to a new error : 

`Error: unknown shorthand flag: 'r' in -rpcwallet=testwallet`

Is this something related to the way I do it or is this a bug ?

**Comment by tiero** [comment]
I found the reason. `-rpcwallet=<walletname>` is not a flag of the command, rather than a goobla argument of the `elements-cli`

With `nigiri rpc --liquid` we wrap the `docker exec ...` command for easy consumption, but we only expose the command and not the global flag.

To use it now with nigiri you should do this

```sh
$  docker exec -it liquid elements-cli -datadir=config -rpcwallet=testwallet getbalance 
```

**Comment by tiero** [comment]
@francismars Will look into it

**Comment by tiero** [comment]
Hello @Mairkur 

I finally added the possibility to specify the `rpcwallet` you want to user when using the `nigiri rpc` command, starting from `v0.0.11`




```sh
# To upgrade latest version
curl https://getnigiri.vulpem.com | bash
nigiri start --liquid

nigiri rpc --rpcwalett="mywallet" getbalance 
```
