### ISSUE TITLE
Add bitcoind/elementsd user+password to env file

### ISSUE THREAD

**Issue by luckysori** [vulpemventures/nigiri#105]
It would be handy to be able to read the RPC user and password from the env file so that an application can communicate directly with the nodes spun up by nigiri.

We can easily hard-code these for now as they're always the same, but I think this addition would be useful!

**Comment by tiero** [comment]
Hey @luckysori thanks for the feedback.

Consider that we already allow you to change/edit the bitcoin.conf/elements.conf files you can find in your nigiri datadir, so if you need different user&password than the default you can already do

But interested to know your use case of using ENV VARS to manipulate the conf files

**Comment by luckysori** [comment]
> Consider that we already allow you to change/edit the bitcoin.conf/elements.conf files you can find in your nigiri datadir, so if you need different user&password than the default you can already do

Thanks for the tip! I had honestly forgotten about these conf files.

> But interested to know your use case of using ENV VARS to manipulate the conf files

What I'm trying to achieve is contacting elementsd via RPC over HTTP without having to hard-code the `rpcuser` and `rpcpassword` i.e. reading them from a file. With your suggestion I can read them from `elements.conf`, so we're good! Although it may be good to add this information to the `.env` file, since that is where I would have expected it to be.
