### ISSUE TITLE
QEMU issue with liquid image on Mac M1

### ISSUE THREAD

**Issue by bilthon** [vulpemventures/nigiri#127]
My `elementsd` process seem to be crashing. The first indication that something is wrong is that the aliased command `ecli getblockchaininfo` just hangs.

A `nigiri logs liquid` gives me this in the last few lines:

```
liquid               | 2021-12-16T02:26:45Z HTTP: starting 4 worker threads
liquid               | 2021-12-16T02:26:45Z Using wallet directory /config/liquidregtest/wallets
liquid               | 2021-12-16T02:26:45Z init message: Verifying wallet(s)...
liquid               | 2021-12-16T02:26:45Z init message: Loading banlist...
liquid               | 2021-12-16T02:26:45Z SetNetworkActive: true
liquid               | 2021-12-16T02:26:45Z Using /16 prefix for IP bucketing
liquid               | Operation not permitted (src/thread.cpp:309)
liquid               | qemu: uncaught target signal 6 (Aborted) - core dumped
```

I think this could be an issue related to the the M1 arch. I've had a similar issue with Polar for lightning.

### Further nigiri details

Version: 0.3.4
Commit: 6088a439cde711058d24bed09f5e46d073ced56f
Date: 2021-11-24T11:54:17Z

**Comment by tiero** [comment]
If you run `nigiri update` there is a new image being pulled?

**Comment by tiero** [comment]
PS: instead of aliasing your own command, you can use the `nigiri rpc --liquid <elements-cli command>` command 

```bash
nigiri rpc --liquid getblockchaininfo
```

**Comment by bilthon** [comment]
Thanks! It's working fine now. I think the `nigiri update` did it!
