### ISSUE TITLE
Config files not found in ~/.nigiri on macOS

### ISSUE THREAD

**Issue by schjonhaug** [vulpemventures/nigiri#131]
README.md says:

> This will create a directory `~/.nigiri` copying there `{bitcoin|elements}.conf` you can modify.

On which OS is that the case? Because this is not what happens on macOS.

On macOS, the config files are found in `~/Library/Application\ Support/Nigiri/volumes/bitcoin/bitcoin.conf` and `~/Library/Application\ Support/Nigiri/volumes/elements/elements.conf` respectively.

Should I make a PR clarifying this?

**Comment by tiero** [comment]
Yes you are right, the $HOME in macos resolves to `~/Library/Application\ Support`

Yes PRs are more than welcome!

**Comment by schjonhaug** [comment]
I think `$HOME` and `~` resolves to the same path on macOS.

```
❯ cd ~
❯ pwd
/Users/schjonhaug
❯ cd $HOME
❯ pwd
/Users/schjonhaug
```

I haven‘t dug into the source code of Nigiri, so I’m not sure where Library/Application Support part comes from. Is that what Golang gives you as value for `$HOME` on macOS?

**Comment by tiero** [comment]
It come from golang `btcutil` package 

https://github.com/btcsuite/btcutil/blob/master/appdata.go#L97-L102

LND, BTCD etc.. bitcoin/golang ecosystem use that so we decided to stick with it.

**Comment by schjonhaug** [comment]
Thanks, I made a PR: https://github.com/vulpemventures/nigiri/pull/132
