### ISSUE TITLE
add `pchMessageStart` in elements.conf file

### ISSUE THREAD

**Issue by louisinger** [vulpemventures/nigiri#133]
I'm working on protocol messages for neutrino-elements. In order to build messages, I need the magic bytes identifying the network. I tried all the magic bytes provided by elements code base but nothing worked with nigiri (even regtest :thinking:). However, it works if the magic bytes are defined manually in the `elements.conf` file, like [liquid testnet](https://liquidtestnet.com/). 
it may be useful to define the nigiri magic bytes using `pchMessageStart` in the conf file. In case of testing, it also ensures that we target the nigiri network.

**Comment by tiero** [comment]
Proposals and Contributions are welcome :)
