### ISSUE TITLE
Cannot start esplora, port 5000 in use on macOS Monterey

### ISSUE THREAD

**Issue by schjonhaug** [vulpemventures/nigiri#135]
When I try to start Nigiri in macOS Monterey (12.1), I get the following error message:

```

❯ nigiri start
[+] Running 3/4
 ⠿ Container bitcoin     Started                                                                                                                                                            0.4s
 ⠿ Container electrs     Started                                                                                                                                                            1.4s
 ⠿ Container chopsticks  Started                                                                                                                                                            2.2s
 ⠋ Container esplora     Starting                                                                                                                                                           0.0s
Error response from daemon: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use
exit status 1
```

I can see the same thing in Docker:

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/84225/148275070-a666749c-4f71-43f4-a8a5-00f25a3a7d10.png">

Seems to be related to macOS Monterey using port 5000, see https://anandtripathi5.medium.com/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c

**Comment by tiero** [comment]
Exactly, it's happened already in new Mac OS. What we did was to disable it `System Preferences --> Sharing --> AirPlay Receiver`

I think is a bummer a system service uses a so low port, so I hope they will change it at some point.

Otherwise, if you really need AirPlay on, you may want to override the `docker-compose` in your datadir https://github.com/vulpemventures/nigiri/blob/master/cmd/nigiri/resources/docker-compose.yml#L110

**Comment by schjonhaug** [comment]
Yes, disabling Airplay Receiver works. Should these workaround options be mentioned in the README perhaps? It’s not obvious what goes wrong.

**Comment by tiero** [comment]
> Should these workaround options be mentioned in the README perhaps? It’s not obvious what goes wrong.

Agreed. Would you been so kind to open a PR for it? :) 

> Alternatively, could Nigiri use another port than 5000?

This should be avoided, lot of apps/devs enviromnets already use this port and expect esplora to be there. Seems something very awkward from Apple, they should fix imho

**Comment by schjonhaug** [comment]
I tried to change the port to 5500 (I kind of picked a random number, should it rather be something else?), like so in
`/Users/schjonhaug/Library/Application Support/Nigiri/docker-compose.yml`:

```
  # Block explorer frontend
  esplora:
    image: ghcr.io/vulpemventures/esplora:latest
    container_name: esplora
    depends_on:
      - chopsticks
    environment: 
        API_URL: http://localhost:3000
    ports:
     - 5500:5500
    restart: unless-stopped
```

 Nigiri starts

```
❯ nigiri start
[+] Running 4/4
 ⠿ Container bitcoin     Running                                           0.0s
 ⠿ Container electrs     Running                                           0.0s
 ⠿ Container chopsticks  Running                                           0.0s
 ⠿ Container esplora     Started                                           2.0s

ENDPOINTS
bitcoin localhost:18443
bitcoin localhost:18444
bitcoin localhost:28332
bitcoin localhost:28333
electrs localhost:50000
electrs localhost:30000
esplora localhost:5500
chopsticks localhost:3000
```

But I cannot load esplora, my browser says that it got an empty response.

**Comment by tiero** [comment]
This what I do:


```
nigiri stop --delete

# Tweak docker-compose in my datadir with 5500

nigiri start

# wait a bit node and electrs goes in sync
# Open http://localhost:5500 in browser

```
