### ISSUE TITLE
Expose -generate flag of bitcoin-cli to `nigiri rpc`

### ISSUE THREAD

**Issue by schjonhaug** [vulpemventures/nigiri#142]
I’m trying to use bitcoin-cli’s `generate` with Nigiri, but to no avail:

```
❯ nigiri rpc generate 10
error code: -1
error message:
generate
has been replaced by the -generate cli option. Refer to -help for more information.
exit status 1

❯ nigiri rpc -generate 10
Incorrect Usage: flag provided but not defined: -generate

NAME:
   nigiri rpc - invoke bitcoin-cli or elements-cli

USAGE:
   nigiri rpc [command options] [arguments...]

OPTIONS:
   --liquid           enable liquid (default: false)
   --rpcwallet value  rpcwallet to be used for node JSONRPC commands
   --help, -h         show help (default: false)

[nigiri] flag provided but not defined: -generate
```

This is what I expect would happen:

```
❯ bitcoin-cli -regtest -generate 10
{
  "address": "bcrt1qpcul9qzkketgqseehq06s75mxcttpv9q4xfpdt",
  "blocks": [
    "7e00a57d010ca30c7e71e797dfddb699abd3537f6dfb1b30d817eef4ee027b00",
    "33c94b24a193edfa8968242df3dc126003bdd3bfa161410988a563537b9bef25",
    "370d4e1f6ac122551f636cc106ce3110d1fd5c37e96c23b952649efdb6186491",
    "5db7c34629421a839c968a3bb10baa44ba7ce98e093146d92eae6f6ee1c79ad6",
    "411d51bed5809c5433e0cca66ee1827f7ce8a172e128a229ad10c68c2fecab70",
    "3c1d97b863da244c707a0cc6aecc6ca4b2dccbc2092c14fa8e68c776635c9c7a",
    "547d72889dd95f03fc0e01766eb74620a3deac7ed40e624ba77dd5a802d3992a",
    "01d4cabae7d491136a52a288b89c8bb1bf080788510f0931335188e92c97140b",
    "7b28cf723ed6f27c2e38cc4fa675dd2a4ea5df23d1148af10f21a97ed2137c0d",
    "3f0a17786b88b141010ff358b2ccefbfdc841928161e09d615dc6661da6de771"
  ]
}
```

**Comment by tiero** [comment]
Interesting, never heard about `-generate` flag, I always used the JSONRPC command `generatetoaddress`

```bash
nigiri rpc generatetoaddress 1 bcrt1qpst8e28pwmz40chjgpqyhukw4muv5835n4e33a
[
  "4b318fa2c2523487886dbdb6a7c53487fccb61d79714bb746d67a5d7d7e95ba3"
]
```

**Comment by tiero** [comment]
About the flag, will not work since how is architected the `nigiri rpc` command: we only pass the acutal command standard input, we have a fixed default for the `bitcoin-cli` flags, if need to expose a flag we should do on purpose and so something like we did for `-rpcwallet` which became `--rpcwallet`

I would use `generatetoaddress` for now

An easy way 

```bash
nigiri rpc generatetoaddress 1 `nigiri rpc getnewaddress`
```

**Comment by schjonhaug** [comment]
Yes, I know about that command. However, it would be great if all commands from `bitcoin-cli` would be available.

**Comment by tiero** [comment]
> Yes, I know about that command. However, it would be great if all commands from `bitcoin-cli` would be available.

Would be acceptable for you to have double dash? `nigiri rpc --generate 10` ?

**Comment by schjonhaug** [comment]
Better than not having access to all commands, for sure :)

**Comment by Janaka-Steph** [comment]
`generate` is the old `generatetoaddress` but it is deprecated now

**Comment by tiero** [comment]
I think `generate` is deprecated, but they added `bitocin-cli -generate <numBlocks>` as flag of root command

Has been added to `nigiri` into #144

**Comment by schjonhaug** [comment]
When will you release a new version of Nigiri? The last one was in December.

**Comment by tiero** [comment]
We release based on bugs or feature requests,  so not really a schedule.

#144 is in review, we could get that sometime next week
