### ISSUE TITLE
When running in ci, docker commands should be run with `-i` not `-it`

### ISSUE THREAD

**Issue by futurepaul** [vulpemventures/nigiri#149]
for example `rpcArgs := []string{"exec", "-it", "lnd", "lncli", "--network=" + network}` should become `rpcArgs := []string{"exec", "-i", "lnd", "lncli", "--network=" + network}`

the `-t` emulates a terminal, but in headless CI that can result in `input device is not a TTY` errors. some relevant discussion here: https://stackoverflow.com/questions/30137135/confused-about-docker-t-option-to-allocate-a-pseudo-tty

**Comment by tiero** [comment]
This should be fixed in `0.4.1`

**Comment by futurepaul** [comment]
you are my hero
