### ISSUE TITLE
Error with newest version of Docker Compose on startup

### ISSUE THREAD

**Issue by noubre** [vulpemventures/nigiri#170]
I can download nigiri just fine, but when I start it up with `nigiri start`, I get this error: [nigiri] exec: "docker-compose": executable file not found in $PATH

I am running Ubuntu 22.04.1 with the newest version of Docker Desktop. After encountering the error, running `docker-compose version` outputs that docker-compose doesn't exist. Then, I remembered that they changed it or something and when I run `docker compose version` it outputs the version. 

I experience the same error even when I uninstall Docker Desktop and use Docker engine. I'm sure I am missing something easy, any help is appreciated.

**Comment by tiero** [comment]
I see the issue: we now use the old CLI `docker-compose`  but we should also support the new one which is a subcommand of docker itself ie. `docker compose` 

Will push a fix to this, to autonativally detect the version of compose you have running ln your system.

**Comment by tiero** [comment]
Can you try to download the latest tagged release? 
https://github.com/vulpemventures/nigiri/releases/tag/v0.4.12

**Comment by noubre** [comment]
It is fixed, and it works great. Thanks!
