### ISSUE TITLE
Using Nigiri without installing the CLI

### ISSUE THREAD

**Issue by gunar** [vulpemventures/nigiri#177]
How do you recommend setting up the development environment for a project that uses `nigiri`? Would you just add to the README instructions that the developer should install the `nigiri` CLI locally? Is there a way to avoid having to install it in the development environment? Can I perhaps simply use/reuse this project's `docker-compose.yml` so that I get everything I need set up with `docker compose up`? And if that's the case, is there some documentation that might help me in doing so?

I understand that's a lot of questions. My hope is that they'll help me convey a sense of what I'm looking for.

Thanks in advance.

**Comment by tiero** [comment]
Hey @gunar the CLI indeed abstracts all docker complexities, orchestrate various containers, and expose useful commands for development.

You can def fork the project and copy the docker-compose, but cant really help more than that as the CLI is built with the sole purpose to make it easier :) I would encourage developers to have nigiri installed on their machine.

We also have a GitHub action (which is pulling the CLi and running all the services without the Esplora frontend) ie. `nigiri start --ci`

**Comment by gunar** [comment]
Thank you. I'll see how far I can take it just with the docker compose file, and if I see myself missing an easy-to-use CLI I'll come back to `nigiri`. Thanks again for your prompt response.
