### ISSUE TITLE
Nigiri Start fails, when a user tries to reinstall nigiri 

### ISSUE THREAD

**Issue by susruth** [vulpemventures/nigiri#192]
* The ghcr images hosted by vulpemventures are not usable
* Anyone who calls ```curl https://getnigiri.vulpem.com | bash``` will not be able to start Nigiri 

It fails with the following error

<img width="781" alt="Screenshot 2024-10-04 at 9 24 35 AM" src="https://github.com/user-attachments/assets/1e8306c3-150a-49e0-9284-084b7652afd8">

**Comment by tiero** [comment]
Thanks for reporting, although looks like a GitHub issue.

**Comment by tiero** [comment]
Can you please try again? It may be Github Container Registry error to me?
<img width="1483" alt="image" src="https://github.com/user-attachments/assets/8c6f361e-0e0a-4de2-b477-ec7caea88def">

**Comment by susruth** [comment]
Getting the same error, this only happens when you remove nigiri and reinstall it 

<img width="870" alt="Screenshot 2024-10-15 at 9 12 43 AM" src="https://github.com/user-attachments/assets/c05671b5-c542-40a3-b525-92f9adfd4bf9">

**Comment by susruth** [comment]
It is on a Macbook Pro ARM64

**Comment by tiero** [comment]
Same here :/

Do you use docker Desktop? Can I suggest OrbStack instead? much more lightweight, and sometimes less buggy

**Comment by susruth** [comment]
Started working with OrbStack, closing this issue, thanks for the help!
