### ISSUE TITLE
Add txindex to elements.conf

### ISSUE THREAD

**Issue by altafan** [vulpemventures/nigiri#68]
After upgrading the version of the elements node I'm not able anymore to use cli commands like `decoderawtransaction` that returns the error `No such mempool transaction. Use -txindex to enable blockchain transaction queries. Use gettransaction for wallet transactions.`

**Comment by tiero** [comment]
Strange because txindex was off even in the past version https://github.com/vulpemventures/nigiri/blob/31dadb20a9ae69659b1db039b0e4cc9ec2ee1ba4/resources/volumes/liquidregtest/liquid-config/liquid.conf#L3
