### ISSUE TITLE
Add Nigiri Travis reference in documentation

### ISSUE THREAD

**Issue by tiero** [vulpemventures/nigiri#74]
We have a completely different version of nigiri to be used inside Travis and other CI services. So the readme should ask "Are you looking to spin-up Nigiri in Travis or Github Action? Look here" and link to https://github.com/vulpemventures/nigiri-travis

**Comment by francismars** [comment]
Where would you like this information to be added? 
On the first section (under "You can have Elements too with the --liquid flag.")
or
In the Footnotes

**Comment by tiero** [comment]
Yes in the header it's better I guess.
