### ISSUE TITLE
Couldn't build Nigiri from source on MacOS

### ISSUE THREAD

**Issue by thunderbiscuit** [vulpemventures/nigiri#77]
Hello, and thanks for building such a cool tool!

I'm currently not quite able to get Nigiri working on my Mac. Not sure why: I clone, install, and build using the readme and it works just fine without any errors, but then the `nigiri` command doesn’t actually show up for the party. I am being told by someone else that the binary should be in `~/bin/`, but it isn't there for me. I assume it didn't manage to build properly, but I'm not sure what I did wrong.

I am wondering if maybe I misunderstood the readme. It mentions _ingredients_ for Nigiri (bitcoind, esplora, etc.), and I took those to be the things that would be bundled in the docker image. Is that maybe not the case, and instead I need to have those installed on my machine prior to running the install script and building the binary?

Cheers!

**Comment by tiero** [comment]
Hello @thunderbiscuit 

I assume you don't want to use the [pre-built binaries](https://github.com/vulpemventures/nigiri#pre-built-binary) and want to [build from source instead.](https://github.com/vulpemventures/nigiri#directions) 

If so, after you run `bash scripts/build darwin amd64` in the project directory, you should be able to enter in the local `./build` folder and grab the binary. It should be called `nigiri-darwin-amd64`. 

PS: Then give it permissions to execute  (eg. `chmod +x ./build/nigiri-darwin-amd64`) and move it to your path (maybe rename it into just nigiri). The sae thing the[ bash one liner ](https://github.com/vulpemventures/nigiri-installer-script/blob/master/index.sh#L115) would have done for you

**Comment by tiero** [comment]
Be sure to not run `scripts/clean` right after :) It would remove the freshly compiled binary. I added a line in the readme to make it more clear that after `scripts/build` you are done and only need to clean if pulling/upgrading a new version of the code :)

**Comment by thunderbiscuit** [comment]
Yes that last "clean" part almost got me. It read a bit like a series of steps to execute so I was about to run it but then realized it didn't make sense. +1 for the updated readme! It's now super clear.

Thanks for the pointers, it works wonders.
