### ISSUE TITLE
Esplora missing `tx/:txid/raw` endpoint

### ISSUE THREAD

**Issue by LLFourn** [vulpemventures/nigiri#85]
```
$ curl http://localhost:3000/tx/983d00aadfd4bdfc37fa6ee992bbbc6f600c69b4e1ebfeca32f0e9ec81efbc43/raw
endpoint does not exist "/tx/983d00aadfd4bdfc37fa6ee992bbbc6f600c69b4e1ebfeca32f0e9ec81efbc43/raw"
```
`/hex` works fine though which is weird. `/raw` is meant to be there too: https://github.com/Blockstream/esplora/blob/master/API.md#get-txtxidhex

**Comment by tiero** [comment]
Hello @LLFourn, thanks for reaching out. I confirm that the version of `electrs` that nigiri exposes does not have that endpoint.

We built and pushed from master 6 months ago. Probably the online version of Blockstream is newer and has this feature. Let me investigate brb

**Comment by tiero** [comment]
PS: cc/ @sheshek Would be nice if you guys could tag a GH release every time you deploy a new version of Electrs on Blockstream.info, so we know when to build it and push a new image for nigiri. Thanks

**Comment by tiero** [comment]
@LLFourn The new image has been pushed. Now the endpoint `tx/:txid/raw` works for me as expected.

If you have already installed nigiri, do this

```sh
# If already running 
$ nigiri stop --delete
# Remove the images
$ docker rmi vulpemventures/electrs vulpemventures/electrs-liquid
# Run again. It pulls the newly tagged images. 
$ nigiri start 
```

**Comment by tiero** [comment]
Closing, for now, let me know if you have any problem with the update.

**Comment by LLFourn** [comment]
Works thanks!
